### ISSUE TITLE
Placement of uni0654 "Arabic Hamza above" with uni0640 "Arabic Tatweel"

### ISSUE THREAD

**Issue by adamiturabi** [silnrsi/font-scheherazade#1]
Sometimes there is a need to place uni0654 "Arabic Hamza above" with uni0640 "Arabic Tatweel" to display inline Hamza. With Scheherazade New, the placement of the hamza is a little too high and the tatweel is also a little too narrow, so that the surrounding diacritics may clash. This image should show what I mean:

![image](https://user-images.githubusercontent.com/61895563/118405219-37a46a80-b690-11eb-9486-f9a282a7a6ea.png)

It will be great if the hamza can be placed a little lower and also the tatweel elongated slightly when this input sequence occurs, to avoid clashing with other diacritics, perhaps like this:

![image](https://user-images.githubusercontent.com/61895563/118405365-0b3d1e00-b691-11eb-8ab4-454bef1ca743.png)

Thank you.

**Comment by LornaSIL** [comment]
Thank you for this report. Can you tell me what application you are using? The positions you are seeing for the combining marks are much higher than what I am seeing. However, I do see the position on a kashida is higher than it should be. We will try to fix it for a subsequent release. We use the kashida for kerning which is why it is so small, but we should be able to do something for cases like this. Of course, you can always insert several kashidas to get the length you wish.

**Comment by adamiturabi** [comment]
Thanks for the quick response. I'm using XeLaTex with polyglossia package to create a PDF, and then opening the PDF in Evine Document Viewer on Ubuntu.

Would you mind sharing a screenshot of how the combining marks display for you? My impression is that PDF should be platform independent.

> but we should be able to do something for cases like this. 

That would be great. Thank you!

> Of course, you can always insert several kashidas to get the length you wish.

I see what you mean but it will be a little cumbersome, because I'm preferring to be able to select one of several well-designed Arabic fonts for my application and it will be convenient to input the text once in a standard way.

**Comment by LornaSIL** [comment]
Thank you for this report. Can you tell me what application you are using? The positions you are seeing for the combining marks are much higher than what I am seeing. However, I do see the position on a kashida is higher than it should be. We will try to fix it for a subsequent release. We use the kashida for kerning which is why it is so small, but we should be able to do something for cases like this. Of course, you can always insert several kashidas to get the length you wish.

**Comment by LornaSIL** [comment]
> Would you mind sharing a screenshot of how the combining marks display for you? My impression is that PDF should be platform independent.

Oh, sorry. What I'm seeing does match your first graphic. I was looking at your second graphic and how the above marks were all at the same position (which is not how we designed Scheherazade).

**Comment by adamiturabi** [comment]
> > Would you mind sharing a screenshot of how the combining marks display for you? My impression is that PDF should be platform independent.
> 
> Oh, sorry. What I'm seeing does match your first graphic. I was looking at your second graphic and how the above marks were all at the same position (which is not how we designed Scheherazade).

Ah, I see. My second graphic was using the Amiri typeface. I only intended to show the positioning of the hamza there. The vowel marks in Amiri are indeed much higher than Scheherazade New as you noted, but that it probably a design choice by the typographer.

**Comment by LornaSIL** [comment]
This has been implemented in the new v4.000 release.
