### ISSUE TITLE
Bosnian specific characters from Arabic Extended-B table not being connected to other letters properly

### ISSUE THREAD

**Issue by programeris** [silnrsi/font-scheherazade#3]
I've used Scheherazade font in Bosnian Arebica converter (https://www.e-bosanski.ba/konverter-pisama/bosanska-arebica/).
I've noticed that Bosnian specific characters (U+0889 and U+088A) from Arabic Extended-B table are not being connected to other letters properly in Webkit browsers (Chrome, Edge etc) and on Windows desktop applications. On Firefox browser it is OK. See examples:

Firefox:
![image](https://user-images.githubusercontent.com/66169674/143722667-9f6c79b2-87cd-4a87-ab2c-a2d3f99a0234.png)
![image](https://user-images.githubusercontent.com/66169674/143722739-16154bed-095d-4bd6-9106-9aa7e6c368bb.png)

Chrome:
![image](https://user-images.githubusercontent.com/66169674/143722682-3669a153-a651-42fc-a7db-8619b5095f71.png)
![image](https://user-images.githubusercontent.com/66169674/143722746-d0448b02-d05e-42a3-9dc9-9db20c61d99d.png)

Microsoft Word:
![image](https://user-images.githubusercontent.com/66169674/143722717-6f773f9d-b6f2-4174-9a49-cc60f8425c45.png)
![image](https://user-images.githubusercontent.com/66169674/143722766-c38cd510-f761-4e24-ba92-1c6165833f58.png)

**Comment by LornaSIL** [comment]
Thanks for your interest in the new version of Scheherazade. Unfortunately, most OpenType applications have not yet been updated to support the new characters in Arabic Extended-B. The font has Graphite and that's why those characters work in Firefox and in LibreOffice. One of the *Known Issues* states: `Many OpenType applications do not yet support Unicode 13.0 or 14.0 and may not correctly handle the characters in ranges U+0870..U+089F, U+08BE..U+08C7, U+FD40..U+FD4F, U+FDCF, and U+FDFE..U+FDFF.`

Hopefully applications will be updated in the near future, but that is not something we can do.

**Comment by programeris** [comment]
Thanks for the explanation!
