### ISSUE TITLE
Asking about design decisions: Maddas and YEH BAREE

### ISSUE THREAD

**Issue by mahalisyarifuddin** [silnrsi/font-scheherazade#4]
Greetings, this is the author of "[Proposal to Encode Characters from Indonesian Orthography of Quran](https://www.unicode.org/L2/L2020/20089-indonesia-quran.pdf)".

Glad to know that Scheherazade now supports Unicode 14 codepoints. But I want to ask some stuffs from this typeface, especially about the design decisions, and by "design", I mean the "skeletal" one, not the stylistic.

First, its about the madda signs:
- I'm curious about the design of ARABIC MADDAH ABOVE. It's very confusable to ARABIC MADDA WAAJIB due to the "heel" shape. Why the shape? Is there any precedents? Because as far as I've observed, many Arabic typefaces made ARABIC MADDAH ABOVE in either with the "heel" leaned to the back or just a simple "tilde".

  I would rather have the ARABIC MADDAH ABOVE shape taken from the below part of ARABIC DOUBLED MADDA/HALF MADDA OVER MADDA.

- The maddas are not relatively similar in size, especially when set into smaller font size: some maddas are bigger than the other.

Second, it's about the final glyph of ARABIC LETTER YEH BAREE. I don't speak Urdu and I don't know whether or not Urdu people like to use this typeface, but it looks so jarring to me. The glyph is fell down from the baseline first before it turning back. Again, why the shape? Is there any precedents? And the jarring shape is virtually nonexistent in Arabic typefaces. Lateef did it right, even some glyphs in this typeface did it right.

Also below I attach the test screenshot. Tested: Scheherazade New 3.300, Microsoft Edge 96.0.1054.34, Windows 7. Text: [here](https://r12a.github.io/pickers/arab-all/?text=%D9%83%D9%8E%D8%A2%20%D8%A1%D9%8E%20%D9%83%D9%8E%D8%A7%E0%A2%9C%D8%A1%D9%8E%20%D9%83%D9%8E%D8%A7%E0%A2%9E%D8%A1%D9%8E%20%D9%83%D9%8E%D8%A7%E0%A2%9F%D8%A1%D9%8E%20%DB%81%DB%92%20%D9%82%D9%84%DB%92%20%DB%97)
![Untitled](https://user-images.githubusercontent.com/42148566/144238745-a1296639-54fb-4e9e-a48b-348196736c48.png)

Thank you.

**Comment by LornaSIL** [comment]
Hi! Thanks for your feedback. The Scheherazade font (and now called Scheherazade New) has been around for at least 20 years and we would not be keen on adjusting the shapes that have been in the font that long. 

The maddah above was designed back then and I don't believe the shape has changed significantly since then. I don't think we would want to change it at this point without a lot of user input. We designed the new characters based on your proposal and with feedback from Roozbeh. I'd be interested in seeing more examples of **all** the maddas in use in the same document to see how the new ones could be better harmonized if needed.

Again for the *yeh barree* this is the design since the beginning of the font. I did look at a few other fonts and most are as you have said. However, **Urdu Naskh Unicode** has a similar design to Scheherazade (top is Scheherazade New and Urdu Naskh Unicode is below).
![image](https://user-images.githubusercontent.com/7071907/144262127-3a5acc8d-4087-478b-a50f-7b13614e6047.png)

Also, I took a look at some old Monotype fonts and this Urdu sample is similar in most instances In the cases where it is not similar (initial seen- final yeh barree) they appear to have special ligatures that prevent the deep shaping. Scheherazade New does not include those ligatures.
![image](https://user-images.githubusercontent.com/7071907/144263014-d6c69b1f-eb9d-42cf-943c-66325b901b2e.png)

We probably would not consider changing the *yeh barree* but if you can find samples of all the maddas in one document, I would be glad to look at how we might better harmonize the design of the new ones.
